---
version: "2"
linters:
  enable:
    - misspell
    - sloglint
  settings:
    errcheck:
      exclude-functions:
        - (layeh.com/radius.ResponseWriter).Write
        - (*layeh.com/radius.PacketServer).Serve
        - (*layeh.com/radius.PacketServer).Shutdown
        - (net.PacketConn).Close
        - (net/http.ResponseWriter).Write
        - (*os.File).Close
formatters:
  enable:
    - gofumpt
