---
linters:
  enable:
    - gofumpt

linters-settings:
  gofumpt:
    module-path: radius-exporter
  errcheck:
    exclude-functions:
      - (layeh.com/radius.ResponseWriter).Write
      - (*layeh.com/radius.PacketServer).Serve
      - (*layeh.com/radius.PacketServer).Shutdown
      - (net.PacketConn).Close
      - (net/http.ResponseWriter).Write
