---
version: 2
project_name: radius-exporter
builds:
  - env:
      - CGO_ENABLED=0
    ldflags: -X main.exporterVersion=v{{.Version}} -X main.exporterSha={{.Commit}}
    flags:
      - -trimpath
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: windows
        goarch: arm
archives:
  - format: binary
release:
  mode: append
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
