---
"on": [push, pull_request]

name: Test
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8

      - name: Run go test
        run: go test -v ./...

      - name: Run go build
        run: go build

      - name: Test with FreeRADIUS
        run: test/test.sh
