---
"on": [push, pull_request]

name: Test
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - name: fmt check
        run: test -z $(gofmt -l .)

      - run: go vet .

      - name: Run go test
        run: go test -v ./...

      - name: Run go build
        run: go build

      - name: Test with FreeRADIUS
        run: test/test.sh
